unpackaged/main/default/objects/Account/fields/Gearset_Team__c.field-meta.xml
<CustomField>
    <fullName>Gearset_Team__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Gearset Team</label>
    <referenceTo>Gearset_Team__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Gearset_Team__c/Gearset_Team__c.object-meta.xml
<CustomObject>
    <label>Gearset Team</label>
    <nameField>
        <label>Gearset Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Gearset Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Gearset_Team__c/fields/Gearset_Team_Id__c.field-meta.xml
<CustomField>
    <fullName>Gearset_Team_Id__c</fullName>
    <externalId>true</externalId>
    <label>Gearset Team Id</label>
    <length>36</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/Loss_Reason__c.field-meta.xml
<CustomField>
    <fullName>Loss_Reason__c</fullName>
    <label>Loss Reason</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Lost to Competitor</fullName>
            </value>
            <value>
                <fullName>Price</fullName>
            </value>
            <value>
                <fullName>No Budget / Lost Funding</fullName>
            </value>
            <value>
                <fullName>No Decision / Non-Responsive</fullName>
            </value>
            <value>
                <fullName>No valid use case</fullName>
            </value>
            <value>
                <fullName>Legal / procurement blocked</fullName>
            </value>
            <value>
                <fullName>Errors</fullName>
            </value>
            <value>
                <fullName>Features missing</fullName>
            </value>
            <value>
                <fullName>Trial solved need so no purchase</fullName>
            </value>
            <value>
                <fullName>Free tier</fullName>
            </value>
            <value>
                <fullName>Churn (UPDATE CHURN SPREADSHEET)</fullName>
            </value>
            <value>
                <fullName>Low probability. Reopen if user signs in</fullName>
            </value>
            <value>
                <fullName>Not ready yet</fullName>
            </value>
            <value>
                <fullName>Coronavirus</fullName>
            </value>
            <value>
                <fullName>Region with low propensity to purchase</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/TestCloseDateIsUpdatedWhenOpIsWon.cls
@isTest
private class TestCloseDateIsUpdatedWhenOpIsWon {
	@isTest
    public static void shouldSetOpportunityCloseDateToTodayIfWon() {
        Gearset_Team__c t = new Gearset_Team__c(
            Gearset_Team_Id__c = '1234'
        );
        upsert t;

        Account a = new Account(
        	Name = 'Test Account'
        );
        a.Gearset_Team__c = t.Id;
        insert a;

        Opportunity o = new Opportunity(
        	Name = 'Test opportunity',
            CloseDate = Date.today().addDays(3),
            StageName = 'Invoice Issued',
            Type = 'New',
            LeadSource = 'Inbound',
            AccountId = a.Id
        );
        insert o;
        
        o.StageName = 'Closed Won';
        update o;
        
        Opportunity updatedOp = [SELECT CloseDate FROM Opportunity WHERE Id = :o.Id];
        System.assertEquals(Date.today(), updatedOp.CloseDate);
    }
    
    @isTest
    public static void shouldSetOpportunityCloseDateToTodayIfLost() {
        Opportunity o = new Opportunity(
        	Name = 'Test opportunity',
            CloseDate = Date.today().addDays(3),
            StageName = 'Invoice Issued',
            LeadSource = 'Inbound',
            Type = 'New'
        );
        insert o;
        
        o.Loss_Reason__c = 'Competitor';
        o.StageName = 'Closed Lost';
        update o;
        
        Opportunity updatedOp = [SELECT CloseDate FROM Opportunity WHERE Id = :o.Id];
        System.assertEquals(Date.today(), updatedOp.CloseDate);
    }
    
    @isTest
    public static void shouldNotSetOpportunityCloseDateIfNotMarkedAsWonOrLost() {
        Date closeDate = Date.today().addDays(3);
        Opportunity o = new Opportunity(
        	Name = 'Test opportunity',
            CloseDate = closeDate,
            StageName = 'Approaching Renewal',
            LeadSource = 'Inbound',
            Type = 'New'
        );
        insert o;
        
        o.StageName = 'Invoice Issued';
        update o;
        
        Opportunity updatedOp = [SELECT CloseDate FROM Opportunity WHERE Id = :o.Id];
        System.assertEquals(closeDate, updatedOp.CloseDate);
    }
}