unpackaged/main/default/objects/Lead/fields/Discovery_notes__c.field-meta.xml
<CustomField>
    <fullName>Discovery_notes__c</fullName>
    <inlineHelpText>Miscellaneous notes that doesn&#39;t fit in the previous categories. Any other information that could be helpful for future reference?</inlineHelpText>
    <label>Discovery notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/How_they_currently_use_Salesforce__c.field-meta.xml
<CustomField>
    <fullName>How_they_currently_use_Salesforce__c</fullName>
    <label>How they currently use Salesforce</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Pains_and_aims__c.field-meta.xml
<CustomField>
    <fullName>Pains_and_aims__c</fullName>
    <inlineHelpText>Why have they started looking at Gearset?</inlineHelpText>
    <label>Pains and aims</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Processes_and_environments__c.field-meta.xml
<CustomField>
    <fullName>Processes_and_environments__c</fullName>
    <inlineHelpText>What processes do they currently have in place for Salesforce deployments? What environments do they currently have to develop in?</inlineHelpText>
    <label>Processes and environments</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Lead/fields/Team_Structure__c.field-meta.xml
<CustomField>
    <fullName>Team_Structure__c</fullName>
    <inlineHelpText>What is their current team structure?</inlineHelpText>
    <label>Team Structure</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/classes/TestLeadUtilities.cls
@isTest
private class TestLeadUtilities {
    @isTest
    public static void shouldSummariseLeadWithAllFields() {
        Lead l = new Lead(
        	LastName = 'Kuiper',
            Company = 'Gearset',
            Discovery_Notes__c = 'Test discovery notes',
            How_they_currently_use_Salesforce__c = 'Test how they currently use Salesforce',
            Pains_and_aims__c = 'Test pains and aims',
            Processes_and_environments__c = 'Test processes and environments',
            Team_structure__c = 'Test team structure'
        );
        
        String summary = LeadUtilities.stakeholderSummary(l);
        
        System.assert(summary.contains('Test discovery notes'));
        System.assert(summary.contains('Test how they currently use Salesforce'));
        System.assert(summary.contains('Test pains and aims'));
        System.assert(summary.contains('Test processes and environments'));
        System.assert(summary.contains('Test team structure'));
    }
    
    @isTest
    public static void shouldHandleLeadWithNoDiscoveryNotes() {
        Lead l = new Lead(LastName = 'Kuiper', Company = 'Gearset');
        String summary = LeadUtilities.stakeholderSummary(l);
        
        System.assert(summary.contains('No notes about current Salesforce use'));
    }
}